include:
  - proxy.yaml

services:
  web:
    build:
      dockerfile: Dockerfile.python
    restart: on-failure
    networks:
      backend:
        ipv4_address: 172.20.0.5
    environment:
      - DB_HOST=db
      - DB_TABLE=requests
      - DB_NAME: ${MYSQL_DATABASE}
      - DB_USER: ${MYSQL_USER}
      - DB_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - db

  db:
    image: mysql:8
    restart: on-failure
    networks:
      backend:
        ipv4_address: 172.20.0.10
    env_file:
      - .env


