include:
  - proxy.yaml

services:
  web:
    build:
      dockerfile: Dockerfile.python
    restart: on-failure
    networks:
      backend:
        ipv4_address: 172.20.0.5
    environment:
      - MYSQL_ROOT_PASSWORD=$(MYSQL_ROOT_PASSWORD)
      - MYSQL_DATABASE=$(MYSQL_DATABASE)
      - MYSQL_USER=$(MYSQL_USER)
      - MYSQL_PASSWORD=$(MYSQL_PASSWORD)
      - DB_HOST=db
      - DB_TABLE=requests
    depends_on:
      - db

  db:
    image: mysql:8
    restart: on-failure
    networks:
      backend:
        ipv4_address: 172.20.0.10
    env_file:
      - .env


